[package]
name = "httpecho"
version = "0.1.0"
authors = ["grenlith <corinne@grenlith.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.4.0"
hyper = "0.12"
mime = "0.3"
futures = "0.1.28"